### ISSUE TITLE
The values of attribute age (antiguedad_dren and antiguedad_dist) are becoming zeros after the first year of simulation.

### ISSUE THREAD

**Issue by abaezacastro** [comses/megadapt#33]

**Comment by cpritcha** [comment]
No longer zero after 3fbcd3d3be3a9ef24680b7666605db82aa045c02. I accidentally deleted the infrastructure aging and sacmex updates. Close if you think it's fixed now.

**Comment by abaezacastro** [comment]
Thanks!
