### ISSUE TITLE
Vulnerability Initial Values

### ISSUE THREAD

**Issue by seanbergin** [comses/megadapt#40]
Vulnerability (for potable and non-potable) starts out high for 2018, drops to 0 for 2019 and then stays at normal levels. Is this an artifact of the model initialization or a larger issue?

**Comment by cpritcha** [comment]
The dropping to zero in the second year is because the water_scarcity_index is initialized to zero in the first year. I'll change that to actually compute the water scarcity index of the initial year.

**Comment by abaezacastro** [comment]
This is also happening with the non_potable_water_vulnerability_index.
Thanks

**Comment by cpritcha** [comment]
Should be fixed now. Days with flooding and ponding values are off but I'll put that in a new issue.
