### ISSUE TITLE
predicted `days_with_ponding` and `days_with_flooding` values differ from given data

### ISSUE THREAD

**Issue by cpritcha** [comses/megadapt#41]
```
  year_sim mean_days_ponding mean_days_flooding
     <dbl>             <dbl>              <dbl>
1     2018             4.75              0.0480
2     2019             0.237             0.251 
3     2020             0.188             0.151 
4     2021             0.248             0.189 
5     2022             0.239             0.167 
6     2023             0.247             0.263 
```

2018 data is given. All years after are simulated.

Need to figure out what is causing the difference.

**Comment by cpritcha** [comment]
What are the measurement units for `inunda` and `encharca`?

**Comment by abaezacastro** [comment]
I translated the description of the variables. https://github.com/comses/megadapt/issues/19#issuecomment-477782288
According to the description, flooding and pondings are represented by the expected frequency of events per year.

**Comment by cpritcha** [comment]
Flooding and ponding definitions are now in the metadata.
