### ISSUE TITLE
Sensitivity Analysis Run - File not found

### ISSUE THREAD

**Issue by cpritcha** [comses/megadapt#53]
Running `sensitivity_analysis_run.R` in a clean environment results in an error

```
Error in gzfile(file, "rb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file 'modelOuts', probable reason 'No such file or directory'
```

Is there any setup required @manuvanegas

**Comment by cpritcha** [comment]
48cf3c794e8d891e9c1aa52e8ada4bd0ecf9962a partially fixed it. Now I'm getting

```
Error in dimnames(Y)[[4]] : subscript out of bounds
```

**Comment by manuvanegas** [comment]
I am not getting that error. The first one you had was because I accidentally left the variable "runMod" as F, when it should be set to T (in sensitivity_analysis_run.R, line 42). Maybe the second one has to do with the way you fixed it?

**Comment by cpritcha** [comment]
Thanks @manuvanegas. I set the `runMod` flag to TRUE and now the `sensitivity_analysis_run.R` file produces output in long form. Closing.
