### ISSUE TITLE
Unable to run the ponding index visualization

### ISSUE THREAD

**Issue by seanbergin** [comses/megadapt#54]
I apologize if this is something you are working on right now. I pulled and rebuilt but get this error:

Line 12
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : object 'create_constant_mental_model_strategies' not found

**Comment by abaezacastro** [comment]
Hi @seanbergin 

What git  branch are you on?

One

**Comment by seanbergin** [comment]
The error that I had mentioned has now been fixed.
