### ISSUE TITLE
Add a metadata table so that experiment runs can found later

### ISSUE THREAD

**Issue by cpritcha** [comses/megadapt#69]
Right now experiment runs create a results table and a parameters table. But there is no information on when the experiment was performed, a short description of why it was performed and who performed it. This information would be helpful to understand experiment run results later.

Thoughts @serranoycandela?

**Comment by serranoycandela** [comment]
I agree, we should have a new tablet for that. And i think that can ve a
general table that links the name of the experiments with that info

**Comment by cpritcha** [comment]
Done.
